version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile-dev
    ports:
      - 3001:3000
    env_file: ./backend/docker/.dev.env
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    image: postgres:13-alpine
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: ./backend/docker/.dev.env
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile-dev
    ports:
      - 3000:3000
    env_file: ./frontend/docker/.dev.env
    depends_on:
      - backend
    restart: unless-stopped