version: '3'

services:
  main:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-dev
    ports:
      - 3000:3000
    env_file: .dev.env
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    image: postgres:11.5-alpine
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .dev.env
    restart: unless-stopped